### ISSUE TITLE
LinterとFormatter

### ISSUE THREAD

**Issue by kawaemon** [brokenManager/devlaza-front#18]
PrettierとかESLintとかを使ってCI組んで自動検査させませんか

**Comment by loxygenK** [comment]
カスなのでよくわかりません…
GitHub Actionの一種ですか？

**Comment by kawaemon** [comment]
説明するより見てもらうのが早いと思ったので、PR出しますね。もちろん気に入らなければCloseしてもらって構いません。
ESLintによるコードの検査とPrettierでのフォーマットがされているかを検査し、報告するようになります。

**Comment by loxygenK** [comment]
***so pro move***
