### ISSUE TITLE
ユーザー詳細ページを作成する

### ISSUE THREAD

**Issue by loxygenK** [brokenManager/devlaza-front#26]
そこそこ重いやつで申し訳なみが深い…
大丈夫そうだったらお願いします

**Comment by loxygenK** [comment]
今見たけどアバウトすぎんなこのIssue？？？？？
分からないことがあったら文句言ってください

**Comment by unios103** [comment]
おっけー
わからないとこはdiscordのDMで聞く

**Comment by unios103** [comment]
このissue閉じますね
