### ISSUE TITLE
プロジェクト作成画面の項目を増やす

### ISSUE THREAD

**Issue by unios103** [brokenManager/devlaza-front#33]
現在だとタグの追加等、プロジェクト画面にある項目の設定をするところがないのでそれを追加してください
プロジェクト作成した時にSNSにシェアするページを挟んだ方がいいと思われる

**Comment by loxygenK** [comment]
やってみます

**Comment by loxygenK** [comment]
`createproj_more" ブランチでやります

**Comment by unios103** [comment]
ごめんまってー、ぼくが今作業してるのマージしないとまずい

**Comment by unios103** [comment]
かわえもんのレビューの内容変更してたの忘れてた

**Comment by loxygenK** [comment]
了解した、待機します

**Comment by unios103** [comment]
マージしたのでこれお願いしますー🙇‍♂️

**Comment by loxygenK** [comment]
ごめんなさい、進捗をしていませんでした
今からします
