### ISSUE TITLE
プロジェクトページのとき、横のスライドバーが表示される

### ISSUE THREAD

**Issue by unios103** [brokenManager/devlaza-front#41]
どこの要素がはみ出ているのかわからないです

**Comment by unios103** [comment]
@loxygenK お願いしてもいいですか？

**Comment by loxygenK** [comment]
わかりました :+1:

**Comment by loxygenK** [comment]
縦のスクロールバーが表示されていると、そのスクロールバーのせいで表示がはみ出て横のスクロールバーが出るみたいです
(他のページでも極端に高さを小さくすると同じことが起こる)

**Comment by unios103** [comment]
あー、でも他のページでは標準的なサイズで開いたら横のスクロールバーは表示されないから、普通に開いたときはプロジェクトページでも横のスライドバーが表示されないようにしたい

**Comment by loxygenK** [comment]
そしたらサイト全体で縦スクロールバーの表示を禁止にしちゃって大丈夫ですか?

**Comment by unios103** [comment]
うーん、、自作する？マウスない人はスクロールバーがあったほうがいいだろうし
なんで縦スクロールバーの幅が無視されるんだろう

**Comment by loxygenK** [comment]
https://github.com/brokenManager/devlaza-front/issues/41#issuecomment-623109013
生きててごめんなさい真逆でした…

横スクロールバー表示禁止はいかがですか…?

**Comment by unios103** [comment]
それでもいいかな
右がスクロールバーに隠れてるのが気になるけど

**Comment by loxygenK** [comment]
`App` クラスに `width: 100vw` を追加すれば回避できるみたいです

**Comment by unios103** [comment]
ま？？！天才

**Comment by loxygenK** [comment]
ごめんなさい全然違いました今試したら悪化してました
探します

**Comment by unios103** [comment]
おけ、おねがいします

**Comment by loxygenK** [comment]
できました！！！！！！！！！！！！！！！！！！！！！！！！！PR投げます！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by unios103** [comment]
ありがとうございます！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by loxygenK** [comment]
#42 
よろしくおねがいします :bow:
